### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by sirtacha** [PidgeonTools/SuperProjectManager#29]
Error when installing.

<img width="742" alt="error" src="https://github.com/PidgeonTools/SuperProjectManager/assets/56415296/324f1fe7-c3f7-456b-8931-98c5e6597087">

Restarted Blender, installed running Blender as administrator, restarted PC, deleted preferences folder, installed clean previous version (3.4.1 / new preferences folder), and couldn't install the addon.

 - OS: windows 11
 - Blender 3.5
 - Addon Version: 1.3.1

Thanks!

**Comment by BlenderDefender** [comment]
Hi @sirtacha,
This has happened quite a few times already. I've planned to fix this in the upcoming version, but for now, the quick fix is as follows:
1. Head to:
```
%username%\Blender Addons Data\blender-project-starter
``` 

2. Open `BPS.json` with Notepad (or any other Text Editor). Maybe you'll be able to restore the contents of it manually.
3. If you're able to restore the content, please make sure it's a valid JSON file. If you don't want to/aren't able to restore the file content, delete `BPS.json`. This should hopefully fix your issue.
I apologize for the inconvenience. If you have further questions, please feel free to reach out again.

**Comment by sirtacha** [comment]
Deleting the BPS.Json file worked, many thanks!

**Comment by BlenderDefender** [comment]
Reopening, because this issue shouldn't require manually deleting `BPS.json` to resolve the problem.
